### ISSUE TITLE
Shot animation

### ISSUE THREAD

**Issue by wrazik** [wrazik/TankBotFight#2]
Spawn "shotThin.png" in front of barrel for a 0.5 second after the shot. New keyboard action can be added - after pressing "space" it can call "shot" method from "Tank".

**Comment by WojtekMs** [comment]
I would like to start working on this issue, could you assign it to me? Additionally I have one question in order to clarify the task. The barrel means the tank gun?

**Comment by wrazik** [comment]
Yes, tank gun. The goal is to spawn this sprite: shotOrange.png at the end of a tank gun for a period of time (50ms? 100ms? Choose what looks best for you!). 

Don't spawn the new thread! Use some flag inside the class that will be set to `true` after shot & set it to `false` after some period of time. How to measure the time? How to store timestamp? I have some idea, but maybe you will find something better? Feel free to ask me on DM if you will have any problem!

**Comment by WojtekMs** [comment]
I created a PR #19 which solves this issue.
