### ISSUE TITLE
SFML Rolling release

### ISSUE THREAD

**Issue by WojtekMs** [wrazik/TankBotFight#37]
What do you think about using SFML library from the latest commit in the master branch? I looked at their repository and it seems that they are pretty close to finishing their work on the 3.0 major release with support for C++17 features. The full port is not yet ready, as you can see here https://github.com/SFML/SFML/pull/1847#. However, I can see that they already added constexpr to some of the basic types like `sf::Vector<T>` and `sf::Rect<T>`.

EDIT: I rushed when I said that they are close to finishing their work, https://en.sfml-dev.org/forums/index.php?topic=24372.0 post from 3.12.2021 said that they are just getting started.. :) After having a second thought perhaps it's not the best idea to be on the latest commit because they can introduce breaking changes in the API.

**Comment by ChrisThrasher** [comment]
API breaking changes are still common in SFML 3 development. More feedback from users would be greatly appreciated but I understand why someone wouldn't quite yet want to track such a quickly moving target. Hopefully in another month or so the biggest API breakages will be behind us and it won't be quite so hard to use this in-development version.

**Comment by wrazik** [comment]
I'm strongly against using last-commit for any library. I would preffer to use more-or-less stable libraries.
