### ISSUE TITLE
Add static analysis with clang-tidy on at least one pipeline

### ISSUE THREAD

**Issue by wrazik** [wrazik/TankBotFight#9]

**Comment by WojtekMs** [comment]
I started working on this issue and created #34 . However I would like to consult:
- should we fail the pipeline if clang-tidy finds any warnings?
- I think that some check rules are a bit redundant (for example modernize-use-trailing-return-type) - should we enable all check rules?

**Comment by wrazik** [comment]
You are the best! 
> should we fail the pipeline if clang-tidy finds any warnings?
No, we don't have to. Warnigs are for us to investigate
> I think that some check rules are a bit redundant (for example modernize-use-trailing-return-type) - should we enable all check rules?
Let's don't be nazis, we should use only things that are helpfull for us!
